---
- hosts: all
  become: true
  tasks:

  - name: update repository index
    ansible.builtin.dnf:
      update_cache: yes  

  - name: Install Apache2 (httpd) package
    ansible.builtin.dnf:
      name: httpd
      state: present


  - name: Install support for PHP
    ansible.builtin.dnf:
      name: php
      state: present
