---
- hosts: all
  become: true
  tasks:

  - name: Install updates for fedora
    ansible.builtin.dnf:
      update_cache: yes
    when: ansible_distribution == "Fedora"


- hosts: db_servers
  become: true
  tasks:

  - name: Install mariadb package on db_servers
    ansible.builtin.dnf:
      name: mariadb
      state: present
    when: ansible_distribution == "Fedora"
    tags: db, fedora


